remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-seo-tag
title: Mnesios doc
description: Mnesios, documentation utilisateur
url: "https://userdoc.mnesios.com/"
baseurl: '/'
permalink: pretty
search_enabled: true
nav_sort: case_insensitive
heading_anchors: true
last_edit_timestamp: false
back_to_top: false
#ga_tracking: UA-2709176-10
#ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)

search:
  heading_level: 2
  previews: 2
  preview_words_before: 3
  preview_words_after: 3
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

aux_links:
  "Ouvrir Mnesios":
    - "https://www.mnesios.com/"
aux_links_new_tab: true

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
